scheme: adhimex

nx: 153 
ny: 153 
xmin: -500. # m
xmax: 500. # m
ymin: -500. # m
ymax: 500. # m
grid_x: lowerleftGP
grid_y: lowerleftGP
BC_x: periodic
BC_y: periodic

dt: 0.2 # s
nt: 500
starttime: 0.

velocity_setting: swift_nondiv_streamfunction

initial_tracer: slotted_cylinders

T: 100. # s
u0: 10. # m/s

nondivergent: True

solver: gmresm

outputdir: swiftnondiv_slotcyl_llgp