# based on Blossey Durran 2008 deformational rotation

scheme: adhimex_adv

nx: 50
ny: 50
xmin: 0. # m
xmax: 1. # m
ymin: 0. # m
ymax: 1. # m
BC_x: periodic
BC_y: periodic
grid_x: uniform
grid_y: cosine4

dt: 0.2 #6. # s
nt: 500 #100
starttime: 0.

velocity_setting: blossey_durran

initial_tracer: initial_blosseydurran
config.T: 100

solver: gmresm

filename: blosseydurran
verbose: True
animate: True
outputdir: blosseydurran_adhimexadv_nt500_ycos4