scheme: adhimex

nx: 128 
ny: 128
xmin: -500. # m
xmax: 500. # m
ymin: -500. # m
ymax: 500. # m
grid_x: uniform
grid_y: uniform
BC_x: periodic
BC_y: periodic

dt: 0.2 # s
nt: 500
starttime: 0.

velocity_setting: swift_div

initial_tracer: sine_swift
T: 100. # s
u0: 10. # m/s

#FCT: True
nondivergent: False

solver: gmresm 

outputdir: swiftdiv_sine_adhimex_unif_nt500