scheme: adhimex

nx: 153 
ny: 153
xmin: -500. # m
xmax: 500. # m
ymin: -500. # m
ymax: 500. # m
grid_x: lowerleftGP
grid_y: lowerleftGP
BC_x: periodic
BC_y: periodic

dt: 0.25 # s
nt: 400
starttime: 0.

velocity_setting: swift_nondiv_streamfunction

initial_tracer: sine_swift
T: 100. # s
u0: 10. # m/s

#FCT: True
nondivergent: True

solver: gmresm 

timing: True
print_error: True
outputdir: timingerror_swiftnondiv_sine_adhimex_ll_nt400dt0_25