
scheme: adhimex

nx: 64 #25 #100 #64 #40 #20 #40 #20 #40
ny: 64 #25 #100 #80 #64 #40 #20 #40 #20 #40
xmin: -500. #0.
xmax: 500. #1000.
ymin: -500. #0.
ymax: 500. #1000.
BC_x: periodic
BC_y: periodic
grid_setting: uniform

dt: 1. #2. #0.5 #1. #2. #2. #1 #2 #1. #2. # s
nt: 100 #5 #50 #200 #100 #50 #100 #50 #19 #50 #100 #100 #50 #32 #50
starttime: 0.

velocity_setting: swift_nondiv_double_streamfunction

initial_tracer: sine_swift #constant
constant_tracer: 1. # kg m-3

mref: 0.5 # kg kg-1
mmag: 0.5 # kg kg-1
u0: 10. # m s-1
T: 100. # s

filename: swift
verbose: True
animate: True
outputdir: test_streamfunction_swiftnondiv-double_adhimex