scheme: adhimex

nx: 64 #50 #10 #100
ny: 64 #50 #10 #100
xmin: -500. # m
xmax: 500. # m
ymin: -500. # m
ymax: 500. # m
BC_x: periodic
BC_y: periodic
grid_setting: uniform

dt: 1. #0.02 #6. # s
nt: 100 #50 #1 #50 #0 #600 #100
starttime: 0.

velocity_setting: swift_nondiv_double_streamfunction #swift_ujet45rev #swift_nondiv_streamfunction #solid_body_rotation

initial_tracer: sine_swift #sine_swift #cosine_bell #gaussian_chenetal2017
#constant_tracer: 0.5

#ujet_max: 1. #1.

T: 100. #10. 
u0: 10. #0.5

filename: chenetal2017
verbose: True
animate: True
outputdir: adhimex_sineswift_swiftnondivdouble_similar_to_presentationNOV2025 #test #swift_weakjet #test #ujet_reversal_umax3