scheme: adhimex # 08-02-2026: changed adhimex to be the constancy-preserving one and adhimex_ncp the non-CP one!

nx: 128 #64 
ny: 128 #64
xmin: -500. # m
xmax: 500. # m
ymin: -500. # m
ymax: 500. # m
grid_x: uniform #cosine4_topleft
grid_y: uniform # linear #cosine4_topleft
BC_x: periodic
BC_y: periodic

dt: 0.2 #2. #0.2 #2. #0.2 #2. #0.2 #2. #0.2 #0.25 #1. #0.2 #0.02 #6. # s
nt: 500 #400 #100 #000 #25 #20 #00 #100 #00 #50 #1 #50 #0 #600 #100
starttime: 0.

velocity_setting: swift_nondiv_streamfunction #strong_convergence #swift_div_on_steroids #_streamfunction #swift_ujet45rev #swift_nondiv_streamfunction #solid_body_rotation
constant_v: 20. 

initial_tracer: slotted_cylinders #sine_swift #constant #sine_swift #constant #sine_swift #sine_swift #sine_swift #cosine_bell #gaussian_chenetal2017
constant_tracer: 0.5

#ujet_max: 1. #1.

T: 100. #10. 
u0: 10. #0. #0.5 with T=100. and u=100. we have Cmax of order 20, which is difficult to converge to.

FCT: True
#FCT_reduced: True
nondivergent: True
#tracermin: 0.
#tracermax: 1.

solver: gmresm

filename: chenetal2017
verbose: True
animate: True
outputdir: slotted_cylinders_swift_adhimex_FCT_nt500 #_global01