
scheme: adimex_upwind

nx: 40
ny: 40
xmin: 0.
xmax: 1.
ymin: 0.
ymax: 1.
BC_x: periodic
BC_y: periodic
grid_setting: uniform

dt: 0.01
nt: 25
starttime: 0.

velocity_setting: constant_v
constant_v: -1.

initial_tracer: sine_xy

verbose: True