scheme: adhimex

nx: 153 
ny: 153
xmin: -500. # m
xmax: 500. # m
ymin: -500. # m
ymax: 500. # m
grid_x: lowerleftGP
grid_y: lowerleftGP
BC_x: periodic
BC_y: periodic

dt: 2. # s
nt: 50
starttime: 0.

velocity_setting: swift_nondiv_streamfunction

initial_tracer: sine_swift
T: 100. # s
u0: 10. # m/s

nondivergent: True

solver: gmresm 

timing: True
print_error: True
outputdir: timing_swiftnondiv_sine_adhimex_ll_nt50dt2_0