scheme: adhimex

nx: 256 
ny: 2560 
xmin: -500. # m
xmax: 500. # m
ymin: -500. # m
ymax: 500. # m
grid_x: uniform
grid_y: uniform
BC_x: periodic
BC_y: periodic

dt: 0.1 # s
nt: 1000
starttime: 0.

velocity_setting: constant_uv
constant_u: 10.
constant_v: 10.

initial_tracer: sine_swift

T: 100. # s
u0: 10. # m/s
nondivergent: True

solver: gmresm
theta_anisotropic: True

outputdir: constantuv_sine_unif_anis_ny2560dt0_1