scheme: adhimex

nx: 153 #128 
ny: 153 #128 
xmin: -500. # m
xmax: 500. # m
ymin: -500. # m
ymax: 500. # m
grid_x: lowerleftGP #uniform
grid_y: lowerleftGP #uniform
BC_x: periodic
BC_y: periodic

dt: 0.2 #0.2 #2. #2. # s
nt: 500 #0 #50 #50
starttime: 0.

velocity_setting: swift_nondiv_streamfunction

initial_tracer: slotted_cylinders

T: 100. # s
u0: 10. # m/s
#thirdordermatrix: True

FCT: True
nondivergent: True

solver: gmresm

outputdir: swiftnondiv_slotcyl_llgp_nt500_FCT_adhimexcubic