# based on Chen et al 2017 solid body rotation

scheme: adhimex_adv

nx: 100
ny: 100
xmin: 0. # m
xmax: 10000. # m
ymin: 0. # m
ymax: 10000. # m
BC_x: periodic
BC_y: periodic
grid_x: uniform
grid_y: cosine4

dt: 3. #1.5 #6. # s
nt: 200 #100
starttime: 0.

velocity_setting: solid_body_rotation

initial_tracer: gaussian_chenetal2017

filename: chenetal2017
verbose: True
animate: True
outputdir: rotation_adhimexadv_nt200_ycos4