scheme: adhimex # 08-02-2026: changed adhimex to be the constancy-preserving one and adhimex_ncp the non-CP one!

nx: 128 #64 
ny: 128 #64
xmin: -500. # m
xmax: 500. # m
ymin: -500. # m
ymax: 500. # m
grid_x: cosine4_topleft #cosine4_topleft #cosine4_topleft
grid_y: cosine4_topleft #cosine4_topleft #cosine4_topleft # linear #cosine4_topleft
BC_x: periodic
BC_y: periodic

dt: 0.5 #1. #0.2 #4. #0.4 #2. #1. # s
nt: 200 #500 #25 #1 #250 #50 #100
starttime: 0.

velocity_setting: swift_div
#constant_v: 20. 

initial_tracer: slotted_cylinders #sine_swift #square_wave_x #slotted_cylinders #sine_swift
constant_tracer: 0.5

#ujet_max: 1. #1.

T: 100. #10. 
u0: 10. #0. #0.5 with T=100. and u=100. we have Cmax of order 20, which is difficult to converge to.

thirdordermatrix: True #True #False
#FCT: True
#FCT_reduced: True
nondivergent: False
#tracermin: 0.
#tracermax: 1. 

solver: gmresm #gcrk #gmresm

filename: chenetal2017
verbose: True
animate: True
outputdir: swiftdiv_slotcyl_adhimex3_c4tl_nt200 #c4tl #_adhimexFCT_main #swiftnondiv_adhimexFCTred_comparetoHW